require File.expand_path('lib/formatadormoeda')
require File.expand_path('lib/midia')
require File.expand_path('lib/livro')
require File.expand_path('lib/dvd')
require File.expand_path('lib/set')
require File.expand_path('lib/relatorio')
require File.expand_path('lib/banco_de_arquivos')